# Generated by Django 5.0 on 2024-01-05 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_userpost_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='like',
            field=models.BooleanField(default=True),
        ),
    ]
