# Generated by Django 5.0 on 2024-01-05 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_userpost_like'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userpost',
            unique_together=set(),
        ),
    ]
